# Generated by Django 2.2.4 on 2020-10-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='r_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
