# Generated by Django 2.2.4 on 2020-10-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0002_auto_20201012_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='r_date',
            field=models.DateTimeField(),
        ),
    ]
